---Game Date---
NDefines.NGame.START_DATE = "2077.1.1.12"
NDefines.NGame.END_DATE = "2100.1.1.1"

---Buildings---
NDefines.NBuildings.MAX_SHARED_SLOTS = 50
NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0.0
NDefines.NBuildings.SUPPLY_ROUTE_RESOURCE_BONUS = 0.0


---Production---
NDefines.MAX_EQUIPMENT_RESOURCES_NEED = 6

NDefines.EQUIPMENT_MODULE_ADD_XP_COST = 5
NDefines.EQUIPMENT_MODULE_REPLACE_XP_COST = 5
NDefines.EQUIPMENT_MODULE_CONVERT_XP_COST = 4
NDefines.EQUIPMENT_MODULE_REMOVE_XP_COST = 0
